import {build} from 'esbuild';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import postcss from 'postcss';
import tailwind from 'tailwindcss';

await mkdir('tests/ui/dist',{recursive:true});await mkdir('test-results/screenshots',{recursive:true});
const mock=resolve('tests/ui/mocks.jsx');
await build({entryPoints:['tests/ui/entry.jsx'],bundle:true,outfile:'tests/ui/dist/app.js',jsx:'automatic',plugins:[{name:'fixture-platform',setup(b){b.onResolve({filter:/^next\/(link|image|navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='next/link'?`export {Link as default} from ${JSON.stringify(mock)}`:a.path==='next/image'?`export {Image as default} from ${JSON.stringify(mock)}`:`export {useSearchParams,useRouter,usePathname} from ${JSON.stringify(mock)}`,loader:'js',resolveDir:process.cwd()}));b.onResolve({filter:/^@\/(app\/actions\/(items|register|auth)|lib\/(data|auth|supabase\/client|supabase\/server))$/},()=>({path:mock}));}}]});
const configBuild=await build({entryPoints:['tailwind.config.ts'],bundle:true,write:false,platform:'node',format:'esm'});
const config=(await import(`data:text/javascript;base64,${Buffer.from(configBuild.outputFiles[0].text).toString('base64')}`)).default;
const css=await postcss([tailwind({...config,content:['src/**/*.{ts,tsx}','tests/ui/*.jsx']})]).process(await readFile('src/app/globals.css','utf8'),{from:undefined});
await writeFile('tests/ui/dist/app.css',css.css);
const server=createServer(async(req,res)=>{try{const name=req.url==='/app.js'?'app.js':req.url==='/app.css'?'app.css':null;res.setHeader('Content-Type',name?.endsWith('.js')?'application/javascript':name?'text/css':'text/html');res.end(name?await readFile(`tests/ui/dist/${name}`):'<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><div id="root"></div><script src="/app.js"></script></html>');}catch{res.statusCode=500;res.end();}});
await new Promise(r=>server.listen(4318,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
  await page.goto('http://127.0.0.1:4318/dashboard');await page.getByText('Recently added',{exact:true}).waitFor();await page.screenshot({path:'test-results/screenshots/dashboard.png',fullPage:true});
  await page.goto('http://127.0.0.1:4318/parts');await page.getByText('112 matching parts').waitFor();await page.screenshot({path:'test-results/screenshots/register.png',fullPage:true});
  await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByText('Page 2 of 3').waitFor();await page.getByRole('button',{name:'MAT-060',exact:true}).scrollIntoViewIfNeeded();
  const scroll=await page.evaluate(()=>scrollY);await page.getByRole('button',{name:'MAT-060',exact:true}).click();await page.getByRole('dialog',{name:'Part details',exact:true}).waitFor();await page.getByRole('button',{name:'Open primary photo and zoom'}).waitFor();
  assert.ok(page.url().includes('page=2')&&page.url().includes('part='));await page.screenshot({path:'test-results/screenshots/detail-drawer.png'});
  await page.getByRole('button',{name:'Open primary photo and zoom'}).click();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByText('150%',{exact:true}).waitFor();
  const lightbox=page.getByRole('dialog',{name:'Primary photo',exact:true});
  const pan=lightbox.locator('.touch-none');const panBox=await pan.boundingBox();await page.mouse.move(panBox.x+150,panBox.y+150);await page.mouse.down();await page.mouse.move(panBox.x+190,panBox.y+180);await page.mouse.up();assert.ok((await lightbox.locator('img').getAttribute('style')).includes('translate(40px, 30px)'));
  await page.getByRole('button',{name:'Reset',exact:true}).click();await page.getByText('100%',{exact:true}).waitFor();
  const cdp=await page.context().newCDPSession(page);const touchPoints=[{id:11,x:panBox.x+100,y:panBox.y+200},{id:12,x:panBox.x+200,y:panBox.y+200}];
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints});touchPoints[1].x+=20;await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints});touchPoints[1].x+=60;await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.getByText('150%',{exact:true}).waitFor();await cdp.detach();
  await page.getByRole('button',{name:'Close Primary photo',exact:true}).focus();await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.closest('dialog')?.getAttribute('aria-label')),'Primary photo');
  await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Primary photo',exact:true}).waitFor({state:'hidden'});assert.ok(await page.getByRole('button',{name:'Open primary photo and zoom'}).evaluate(el=>el===document.activeElement));
  await page.getByRole('button',{name:'Edit details',exact:true}).click();await page.getByLabel('Material Description',{exact:true}).fill('Updated bearing assembly');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Changes saved.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Close Part details',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(page.url().includes('page=2'));assert.equal(await page.evaluate(()=>scrollY),scroll);await page.getByRole('button',{name:'Updated bearing assembly',exact:true}).waitFor();
  await page.goForward();await page.getByRole('dialog',{name:'Part details',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.goto('http://127.0.0.1:4318/parts/new');await page.getByLabel('Material Number',{exact:true}).fill('MAT-001');await page.getByLabel('Material Description',{exact:true}).fill('Hydraulic pump assembly');await page.getByRole('button',{name:'Save Part',exact:true}).click();await page.getByRole('dialog',{name:'Possible duplicate parts',exact:true}).waitFor();await page.screenshot({path:'test-results/screenshots/duplicate-warning.png'});
  await page.getByRole('button',{name:'View existing',exact:true}).click();await page.getByRole('dialog',{name:'Part details',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.getByLabel('Material Number',{exact:true}).inputValue(),'MAT-001');
  await page.getByRole('button',{name:'Save Part',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Continue as new part',exact:true}).click();await page.waitForFunction(()=>window.lastCreated);assert.equal(await page.evaluate(()=>window.lastCreated.p_confirm_duplicate),true);
  await page.goto('http://127.0.0.1:4318/parts/new');await page.getByLabel('Material Number',{exact:true}).fill('MAT-001');await page.getByRole('button',{name:'Save Part',exact:true}).click();await page.getByLabel('Quantity to add to selected part').fill('3');await page.getByRole('button',{name:'Add stock to existing',exact:true}).click();await page.waitForFunction(()=>window.lastStockAddition);assert.equal(await page.evaluate(()=>window.lastStockAddition.quantity),3);
  await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4318/parts');await page.getByText('112 matching parts').waitFor();await page.screenshot({path:'test-results/screenshots/mobile-register.png',fullPage:true});await page.getByRole('button',{name:'Filters',exact:true}).click();await page.getByRole('dialog').getByLabel('Location',{exact:true}).selectOption('North yard');await page.getByRole('button',{name:'Show results',exact:true}).click();await page.getByText('56 matching parts').waitFor();
  await page.getByRole('button',{name:/Hydraulic pump assembly/}).click();await page.getByRole('button',{name:'Open primary photo and zoom'}).waitFor();await page.screenshot({path:'test-results/screenshots/mobile-detail.png'});
  const box=await page.getByRole('dialog',{name:'Part details',exact:true}).boundingBox();assert.equal(box.width,390);
  await page.getByLabel('Add a note',{exact:true}).fill('Mobile inspection complete');await page.getByRole('button',{name:'Add note',exact:true}).click();await page.getByText('Note added.',{exact:true}).waitFor();await page.getByRole('dialog',{name:'Part details',exact:true}).getByText('Mobile inspection complete',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Close Part details',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.setViewportSize({width:820,height:1180});await page.goto('http://127.0.0.1:4318/parts');await page.getByText('112 matching parts').waitFor();await page.screenshot({path:'test-results/screenshots/tablet-register.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(errors,[]);console.log('UI checks passed: desktop/mobile register, pagination/scroll, drawer/back-forward, edit, nested photo Escape/focus, duplicate preview/cancel/continue/add stock.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
