"use client";
import { useState } from "react";
import type { DuplicateItem, Role } from "@/lib/types";
import { Dialog } from "./dialog";
import { ItemImage } from "./item-image";
import { PartDrawer } from "./part-detail";
import { addStock } from "@/app/actions/items";
import { titleForItem } from "@/lib/utils";

export function DuplicateDialog({items,role,close,continueNew,stockAdded}:{items:DuplicateItem[];role:Role;close:()=>void;continueNew:()=>void;stockAdded:(id:string)=>void}) {
  const [selected,setSelected]=useState(items[0]?.id||'');const [view,setView]=useState<string|null>(null);
  const [quantity,setQuantity]=useState('1');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [confirmed,setConfirmed]=useState(false);
  return <Dialog title="Possible duplicate parts" close={()=>{if(!busy)close();}}><p className="mb-4 text-sm text-slate-600">These parts may already cover this item. Review a match, add stock, or confirm that this should be a separate record. Your form and photos are kept.</p><div className="space-y-3">{items.map(item=><article className="card p-4" key={item.id}><label className="flex cursor-pointer items-start gap-3"><input type="radio" name="duplicate-part" className="mt-3 h-5 w-5 shrink-0" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><ItemImage src={item.item_photos?.[0]?.signed_url} alt="" className="h-16 w-16 shrink-0 rounded-lg"/><div className="min-w-0"><p className="text-xs font-bold text-forest-700">{item.reason}{item.reason==='Similar description'?` · ${item.similarity_label}`:''}</p><p className="mt-1 break-words text-sm font-bold">{item.material_number||'No material number'}</p><p className="mt-1 break-words text-sm">{titleForItem(item)}</p><p className="mt-2 text-xs text-slate-600">{item.available_quantity??'Unquantified'} available · {item.location||'No location'} · {item.condition}</p>{item.wo_number&&<p className="mt-1 text-xs text-slate-600">WO {item.wo_number}</p>}</div></label><button className="btn-secondary mt-3 min-h-11 text-xs" onClick={()=>setView(item.id)}>View existing</button></article>)}</div><div className="mt-5 border-t pt-5"><label className="label" htmlFor="quantity-added">Quantity to add to selected part</label><input id="quantity-added" className="field" type="number" min="1" max="2147483647" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/><button className="btn-primary mt-3" disabled={busy||!selected} onClick={async()=>{setBusy(true);setError('');try{const result=await addStock(selected,Number(quantity));if(result.error)setError(result.error);else stockAdded(selected);}catch{setError('Unable to confirm the stock addition. Check the part history before retrying.');}finally{setBusy(false);}}}>{busy?'Adding stock…':'Add stock to existing'}</button></div><label className="mt-5 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 h-5 w-5" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the matches and want to create a separate part.</label><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" disabled={!confirmed||busy} onClick={continueNew}>Continue as new part</button><button className="btn-secondary" disabled={busy} onClick={close}>Cancel</button></div>{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{view&&<PartDrawer key={view} id={view} role={role} close={()=>setView(null)}/>}</Dialog>;
}
