import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { ItemImage } from "./item-image";
import { ConditionPill, EmptyState, StatusPill } from "./ui";
import type { Item } from "@/lib/types";
import { availableQuantity, itemStatus, titleForItem } from "@/lib/utils";

export function PartsRegister({ items, removed, manualRemoved }: { items: Item[]; removed: Record<string, number>; manualRemoved: Set<string> }) {
  if (!items.length) return <EmptyState title="No parts found" description="Try another search, or add a new part to the catalogue." href="/parts/new" action="Add Part" />;
  return <>
    <div className="space-y-3 md:hidden">{items.map((item) => { const qty = availableQuantity(item.quantity, removed[item.id] || 0); const gone = itemStatus(item.quantity, removed[item.id] || 0, manualRemoved.has(item.id)) !== "Available"; return <Link href={`/parts/${item.id}`} key={item.id} className="card flex gap-3 p-3 active:bg-slate-50"><ItemImage src={item.item_photos?.[0]?.signed_url} alt="" className="h-20 w-20 shrink-0 rounded-xl"/><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><p className="line-clamp-2 flex-1 text-sm font-bold leading-5">{titleForItem(item)}</p><ArrowRight className="mt-0.5 h-4 w-4 shrink-0 text-slate-300"/></div><p className="mt-1 text-xs text-slate-500">{item.material_number || item.wo_number || "No reference number"}</p><p className="mt-2 flex items-center gap-1 truncate text-xs text-slate-500"><MapPin className="h-3.5 w-3.5 shrink-0"/>{item.location || "No location"}</p><div className="mt-2 flex items-center justify-between"><ConditionPill condition={item.condition}/><span className="text-xs font-bold text-slate-600">{qty === null ? (gone ? "Removed" : "Qty not set") : `${qty} available`}</span></div></div></Link>; })}</div>
    <div className="card hidden overflow-hidden md:block"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="border-b border-slate-200 bg-slate-50/80 text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Part</th><th className="px-4 py-4">Reference</th><th className="px-4 py-4">Location</th><th className="px-4 py-4">Condition</th><th className="px-4 py-4 text-right">Available</th><th className="px-4 py-4">Status</th><th/></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => { const qty=availableQuantity(item.quantity, removed[item.id]||0); const gone=itemStatus(item.quantity, removed[item.id]||0,manualRemoved.has(item.id))!=="Available"; return <tr key={item.id} className="group hover:bg-slate-50"><td className="px-5 py-3"><Link href={`/parts/${item.id}`} className="flex items-center gap-3"><ItemImage src={item.item_photos?.[0]?.signed_url} alt="" className="h-11 w-11 shrink-0 rounded-lg"/><span className="max-w-xs text-sm font-bold group-hover:text-forest-700">{titleForItem(item)}</span></Link></td><td className="px-4 py-3 text-sm text-slate-600"><p>{item.material_number || "—"}</p>{item.wo_number && <p className="mt-0.5 text-xs text-slate-400">WO {item.wo_number}</p>}</td><td className="max-w-[220px] px-4 py-3 text-sm text-slate-600">{item.location || "—"}</td><td className="px-4 py-3"><ConditionPill condition={item.condition}/></td><td className="px-4 py-3 text-right text-sm font-bold">{qty ?? "—"}</td><td className="px-4 py-3"><StatusPill removed={gone}/></td><td className="px-5 py-3"><Link href={`/parts/${item.id}`} aria-label="View part"><ArrowRight className="h-4 w-4 text-slate-300 group-hover:text-forest-600"/></Link></td></tr>; })}</tbody></table></div></div>
  </>;
}
