"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Camera, ImagePlus, LoaderCircle, Save, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { DuplicateDialog } from "./duplicate-dialog";
import { findDuplicates } from "@/app/actions/register";
import type { DuplicateItem, Role } from "@/lib/types";
import { itemSchema } from "@/lib/validation";

type Preview = { file: File; url: string };
export function PartForm({ organisationId, role }: { organisationId: string; role: Role }) {
  const router = useRouter(); const cameraRef = useRef<HTMLInputElement>(null); const libraryRef = useRef<HTMLInputElement>(null);
  const [photos,setPhotos]=useState<Preview[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const formRef=useRef<HTMLFormElement>(null);const photoRef=useRef(photos);const duplicateTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const duplicateSequence=useRef(0);const confirmed=useRef(false);
  const [matches,setMatches]=useState<DuplicateItem[]|null>(null);const [hint,setHint]=useState(0);
  useEffect(()=>{photoRef.current=photos;},[photos]);
  useEffect(()=>()=>{photoRef.current.forEach(p=>URL.revokeObjectURL(p.url));if(duplicateTimer.current)clearTimeout(duplicateTimer.current);},[]);
  function scheduleCheck(event:React.FormEvent<HTMLFormElement>){confirmed.current=false;const name=(event.target as HTMLInputElement).name;if(name!=="material_number"&&name!=="material_description")return;const seq=++duplicateSequence.current;if(duplicateTimer.current)clearTimeout(duplicateTimer.current);duplicateTimer.current=setTimeout(async()=>{const fd=new FormData(formRef.current!);try{const result=await findDuplicates(String(fd.get("material_number")||""),String(fd.get("material_description")||""));if(seq===duplicateSequence.current)setHint(result.items.length);}catch{if(seq===duplicateSequence.current)setHint(0);}},600);}
  function addFiles(files: FileList|null){ if(!files)return; const valid=Array.from(files).filter(f=>f.type.startsWith("image/")); setPhotos(prev=>[...prev,...valid.slice(0,8-prev.length).map(file=>({file,url:URL.createObjectURL(file)}))]); }
  function remove(index:number){ setPhotos(prev=>{ URL.revokeObjectURL(prev[index].url); return prev.filter((_,i)=>i!==index); }); }
  async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); setError(""); const fd=new FormData(e.currentTarget); const parsed=itemSchema.safeParse(Object.fromEntries(fd.entries())); if(!parsed.success){setError(parsed.error.issues[0]?.message||"Check the form and try again.");return;} const d=parsed.data; if(!d.wo_number&&!d.material_number&&!d.material_description&&!d.location&&!photos.length){setError("Add a WO number, material number, description, location or at least one photo.");return;} setBusy(true); if(duplicateTimer.current)clearTimeout(duplicateTimer.current);const allowDuplicate=confirmed.current;confirmed.current=false;const supabase=createClient(); const itemId=crypto.randomUUID(); const paths:string[]=[];
    try { const duplicates=await findDuplicates(d.material_number||"",d.material_description||"");if(duplicates.error)throw new Error(duplicates.error);if(duplicates.items.length&&!allowDuplicate){setMatches(duplicates.items);setBusy(false);return;}for(let i=0;i<photos.length;i++){const ext=(photos[i].file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,""); const path=`${organisationId}/items/${itemId}/${crypto.randomUUID()}.${ext}`; const {error:uploadError}=await supabase.storage.from("item-photos").upload(path,photos[i].file,{cacheControl:"3600",upsert:false}); if(uploadError)throw uploadError; paths.push(path);}
      const {error:dbError}=await supabase.rpc("create_item",{p_id:itemId,p_organisation_id:organisationId,p_wo_number:d.wo_number,p_material_number:d.material_number,p_material_description:d.material_description,p_location:d.location,p_quantity:d.quantity,p_condition:d.condition,p_notes:d.notes,p_photo_paths:paths,p_confirm_duplicate:allowDuplicate}); if(dbError){if(dbError.message.includes("DUPLICATES_FOUND")){const latest=await findDuplicates(d.material_number||"",d.material_description||"");if(latest.error)throw new Error(latest.error);if(latest.items.length)setMatches(latest.items);}throw new Error(dbError.message.includes("DUPLICATES_FOUND")?"A possible duplicate was added while you were saving. Review the matches.":dbError.message);} router.push(`/parts/${itemId}?created=1`); router.refresh();
    } catch(err){ if(paths.length) await supabase.storage.from("item-photos").remove(paths); setError(err instanceof Error?err.message:"Unable to save the part."); setBusy(false); }
  }
  return <><form ref={formRef} onSubmit={submit} onChange={scheduleCheck} className="space-y-6">
    <section className="card overflow-hidden"><div className="border-b border-slate-100 px-4 py-4 sm:px-6"><h2 className="font-bold">Photos</h2><p className="mt-1 text-xs text-slate-500">Add up to 8 photos. The first will be the main photo.</p></div><div className="p-4 sm:p-6">
      {photos.length>0&&<div className="mb-4 grid grid-cols-3 gap-2 sm:grid-cols-4">{photos.map((photo,index)=><div key={photo.url} className="relative aspect-square overflow-hidden rounded-xl bg-slate-100"><Image src={photo.url} alt={`Photo preview ${index+1}`} fill unoptimized className="object-cover"/>{index===0&&<span className="absolute left-2 top-2 rounded bg-forest-900/85 px-2 py-1 text-[10px] font-bold text-white">MAIN</span>}<button type="button" onClick={()=>remove(index)} className="absolute bottom-2 right-2 grid h-9 w-9 place-items-center rounded-full bg-white text-red-600 shadow" aria-label="Remove photo"><Trash2 className="h-4 w-4"/></button></div>)}</div>}
      <div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>cameraRef.current?.click()} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-forest-300 bg-forest-50 text-sm font-bold text-forest-800 hover:bg-forest-100"><Camera className="h-6 w-6"/>Take Photo</button><button type="button" onClick={()=>libraryRef.current?.click()} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 text-sm font-bold text-slate-700 hover:bg-slate-100"><ImagePlus className="h-6 w-6"/>Add Photos</button></div>
      <input ref={cameraRef} className="sr-only" type="file" accept="image/*" capture="environment" onChange={e=>{addFiles(e.target.files);e.target.value=""}}/><input ref={libraryRef} className="sr-only" type="file" accept="image/*" multiple onChange={e=>{addFiles(e.target.files);e.target.value=""}}/>
    </div></section>
    <section className="card p-4 sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><Field label="WO Number" name="wo_number" placeholder="e.g. 45012345"/><Field label="Material Number" name="material_number" placeholder="e.g. 10038472"/><div className="sm:col-span-2"><Field label="Material Description" name="material_description" placeholder="Describe the part"/></div><div className="sm:col-span-2"><Field label="Location" name="location" placeholder="e.g. North Laydown - Row 4 - Bay B"/></div><Field label="Quantity" name="quantity" type="number" min="0" step="1" inputMode="numeric" placeholder="Optional"/><div><label className="label" htmlFor="condition">Condition</label><select className="field" id="condition" name="condition" defaultValue="Good"><option>New</option><option>Good</option><option>Requires Inspection</option></select></div><div className="sm:col-span-2"><label className="label" htmlFor="notes">Notes</label><textarea className="field min-h-28 resize-y py-3" id="notes" name="notes" maxLength={5000} placeholder="Optional observations, dimensions or handling details"/></div></div></section>
    {hint>0&&<p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{hint} possible duplicate{hint===1?"":"s"} found. You can review them when you save.</p>}
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>}
    <div className="sticky bottom-20 z-10 -mx-4 border-t border-slate-200 bg-canvas/95 p-4 backdrop-blur lg:static lg:mx-0 lg:border-0 lg:bg-transparent lg:p-0"><button disabled={busy} className="btn-primary w-full sm:ml-auto sm:flex sm:w-auto sm:min-w-44">{busy?<LoaderCircle className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}{busy?"Saving part…":"Save Part"}</button></div>
  </form>{matches&&<DuplicateDialog items={matches} role={role} close={()=>setMatches(null)} continueNew={()=>{confirmed.current=true;setMatches(null);formRef.current?.requestSubmit();}} stockAdded={id=>{setMatches(null);router.push('/parts/'+id);router.refresh();}}/>}</>;
}
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <div><label className="label" htmlFor={String(props.name)}>{label}</label><input className="field" id={String(props.name)} {...props}/></div>}
