"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import type { Item, Role } from "@/lib/types";
import { loadRegister } from "@/app/actions/register";
import { registerQuery } from "@/lib/register-state";
import { availableQuantity, formatDate, itemStatus, titleForItem } from "@/lib/utils";
import { Dialog } from "./dialog";
import { PartDrawer } from "./part-detail";
import { ItemImage } from "./item-image";
import { ConditionPill, StatusPill } from "./ui";

type Options={locations:string[];creators:{id:string;name:string}[]};
const columns=[['material_number','Material','material'],['material_description','Description','description'],['wo_number','WO','wo'],['location','Location','location'],['condition','Condition','condition'],['available_quantity','Available','quantity'],['status','Status','status'],['created_at','Date added','date'],['creator_name','Added by','creator'],['latest_note','Latest note','notes']] as const;
export function RegisterWorkspace({role,options}:{role:Role;options:Options}) {
  const search=useSearchParams();const query=registerQuery(search.toString());const selected=search.get('part');
  const [result,setResult]=useState<{items:Item[];total:number;error?:string;query:string}>({items:[],total:0,query:"__loading"});
  const [filterOpen,setFilterOpen]=useState(false);
  const [draft,setDraft]=useState<Record<string,string>>(Object.fromEntries(new URLSearchParams(query)));
  const [previousQuery,setPreviousQuery]=useState(query);
  if(previousQuery!==query){setPreviousQuery(query);setDraft(Object.fromEntries(new URLSearchParams(query)));}
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
  useEffect(()=>{let active=true;loadRegister(query).then(r=>{if(active)setResult({...r,query});}).catch(()=>{if(active)setResult({items:[],total:0,query,error:"Unable to load the register. Try again."});});return()=>{active=false;};},[query]);
  function navigate(values:Record<string,string>){const params=new URLSearchParams();for(const [key,value] of Object.entries(values))if(value)params.set(key,value);window.history.pushState(null,'',`/parts?${params}`);}
  function change(key:string,value:string,immediate=false){const next={...draft,[key]:value,page:"1"};setDraft(next);if(timer.current)clearTimeout(timer.current);if(immediate)navigate(next);else timer.current=setTimeout(()=>navigate(next),400);}
  function clear(){if(timer.current)clearTimeout(timer.current);const next={sort:draft.sort||"created_at",direction:draft.direction||"desc"};setDraft(next);navigate(next);}
  const updated=useCallback((item:Item)=>setResult(old=>({...old,items:old.items.filter(i=>i.id!==item.id||!item.is_archived).map(i=>{if(i.id!==item.id)return i;const active=(item.item_movements||[]).filter(m=>m.status==='active');const removed=active.reduce((s,m)=>s+(m.quantity_removed||0),0);return {...i,...item,available_quantity:availableQuantity(item.quantity,removed),status:itemStatus(item.quantity,removed,active.some(m=>m.movement_type==='manual_removal'))==='Available'?'available':'removed',latest_note:item.item_notes?.[0]?.note_text,latest_note_at:item.item_notes?.[0]?.created_at};}),total:old.total-(item.is_archived?1:0)})),[]);
  function open(id:string){if(timer.current)clearTimeout(timer.current);const params=new URLSearchParams();for(const [key,value] of Object.entries(draft))if(value)params.set(key,value);params.set('part',id);window.history.pushState({sparezDrawer:true},'',`/parts?${params}`);}
  function close(){if(window.history.state?.sparezDrawer)window.history.back();else {const params=new URLSearchParams(window.location.search);params.delete('part');window.history.replaceState(null,'',`/parts?${params}`);}}
  function input(name:string,label:string,type='text'){return <input aria-label={label} type={type} min={type==='number'?0:undefined} step={type==='number'?1:undefined} className="filter-field" value={draft[name]||''} onChange={e=>change(name,e.target.value)} placeholder={label}/>;}
  function select(name:string,label:string,opts:{value:string;label:string}[]){return <select className="filter-field" aria-label={label} value={draft[name]||''} onChange={e=>change(name,e.target.value,true)}><option value="">All {label.toLowerCase()}</option>{opts.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>;}
  function filter(name:string,label:string){if(name==='quantity')return <div className="flex gap-1">{input('min','Minimum available','number')}{input('max','Maximum available','number')}</div>;if(name==='date')return <div className="flex gap-1">{input('from','Added from','date')}{input('to','Added through','date')}</div>;if(name==='condition')return select(name,label,['New','Good','Requires Inspection'].map(v=>({value:v,label:v})));if(name==='status')return select(name,label,[{value:'available',label:'Available'},{value:'removed',label:'Fully used / removed'}]);if(name==='location')return select(name,label,options.locations.map(v=>({value:v,label:v})));if(name==='creator')return select(name,label,options.creators.map(v=>({value:v.id,label:v.name})));return input(name,`Filter ${label.toLowerCase()}`);}
  const page=Number(draft.page)||1;const loading=result.query!==query;
  const active=Object.entries(draft).filter(([k,v])=>v&&!['page','sort','direction'].includes(k)).length;
  return <><div className="mb-5 flex flex-wrap items-center gap-3"><input className="field min-w-0 flex-1 basis-72" aria-label="Search parts" placeholder="Search material number, description, WO, location or notes…" value={draft.q||''} onChange={e=>change('q',e.target.value)}/><button className="btn-secondary md:hidden" onClick={()=>setFilterOpen(true)}>Filters {active?`(${active})`:''}</button>{active>0&&<button className="btn-secondary" onClick={clear}>Clear filters ({active})</button>}</div>
    <div className="mb-3 flex flex-wrap items-center justify-between gap-3 text-sm"><p role="status">{loading?'Loading parts…':`${result.total.toLocaleString()} matching parts`}</p><label className="flex items-center gap-2 md:hidden">Sort<select className="filter-field" value={draft.sort||'created_at'} onChange={e=>change('sort',e.target.value,true)}>{columns.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className="btn-secondary px-3" aria-label="Reverse sort direction" onClick={()=>change('direction',draft.direction==='asc'?'desc':'asc',true)}>{draft.direction==='asc'?'↑':'↓'}</button></label></div>
    {result.error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{result.error}</p>}
    <div aria-busy={loading} className="card hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50"><tr>{columns.map(([key,label])=><th key={key} aria-sort={(draft.sort||'created_at')===key?draft.direction==='asc'?'ascending':'descending':'none'} className="px-3 pt-2"><button className="flex min-h-11 items-center gap-2 whitespace-nowrap text-xs font-bold" onClick={()=>{const next={...draft,sort:key,direction:(draft.sort||'created_at')===key&&draft.direction!=='asc'?'asc':'desc',page:'1'};if(timer.current)clearTimeout(timer.current);navigate(next);}}>{label}{(draft.sort||'created_at')===key?(draft.direction==='asc'?' ↑':' ↓'):''}</button></th>)}</tr><tr>{columns.map(([,label,name])=><th className="px-3 pb-3" key={name}>{filter(name,label)}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.items.map(item=><tr key={item.id} className={selected===item.id?'bg-forest-50':'hover:bg-forest-50/50'}><td className="px-3 py-3"><button className="flex min-h-11 items-center gap-3 text-left font-semibold text-forest-700" onClick={()=>open(item.id)}><ItemImage src={item.item_photos?.[0]?.signed_url} alt="" className="h-12 w-12 shrink-0 rounded-lg"/>{item.material_number||'View part'}</button></td><td className="min-w-56 px-3 py-3"><button className="min-h-11 text-left" onClick={()=>open(item.id)}>{item.material_description||'Unlabelled part'}</button></td><td className="px-3 py-3">{item.wo_number||'—'}</td><td className="px-3 py-3">{item.location||'—'}</td><td className="px-3 py-3"><ConditionPill condition={item.condition}/></td><td className="px-3 py-3 font-bold">{item.available_quantity??'Not set'}</td><td className="px-3 py-3"><StatusPill removed={item.status==='removed'}/></td><td className="whitespace-nowrap px-3 py-3">{formatDate(item.created_at)}</td><td className="px-3 py-3">{item.creator_name||'Unknown'}</td><td className="min-w-56 px-3 py-3"><p className="line-clamp-2 break-words">{item.latest_note||'—'}</p></td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden" aria-busy={loading}>{result.items.map(item=><button key={item.id} onClick={()=>open(item.id)} className="card flex w-full gap-3 p-3 text-left"><ItemImage src={item.item_photos?.[0]?.signed_url} alt="" className="h-20 w-20 shrink-0 rounded-lg"/><div className="min-w-0 flex-1"><p className="line-clamp-2 font-bold">{titleForItem(item)}</p><p className="mt-1 truncate text-xs text-slate-600">{item.material_number} · {item.location||'No location'}</p><p className="mt-2 text-xs font-semibold">{item.available_quantity??'Unquantified'} · {item.status==='removed'?'Removed':'Available'}</p><div className="mt-2"><ConditionPill condition={item.condition}/></div></div></button>)}</div>
    {!loading&&!result.error&&!result.items.length&&<div className="card mt-4 p-8 text-center"><h2 className="font-bold">No parts found</h2><p className="mt-2 text-sm text-slate-600">Adjust your filters or add a part.</p><Link className="btn-primary mt-4" href="/parts/new">Add part</Link></div>}
    <nav aria-label="Register pages" className="mt-5 flex items-center justify-between gap-3"><button className="btn-secondary" disabled={loading||page<=1} onClick={()=>navigate({...draft,page:String(page-1)})}>Previous</button><p className="text-sm">Page {page} of {Math.max(1,Math.ceil(result.total/50))}</p><button className="btn-secondary" disabled={loading||page*50>=result.total} onClick={()=>navigate({...draft,page:String(page+1)})}>Next</button></nav>
    {filterOpen&&<Dialog title="Register filters" close={()=>setFilterOpen(false)} sheet><div className="space-y-5">{columns.map(([,label,name])=><div key={name}><p className="label">{label}</p>{filter(name,label)}</div>)}<button className="btn-secondary" onClick={clear}>Clear filters</button><button className="btn-primary ml-2" onClick={()=>setFilterOpen(false)}>Show results</button></div></Dialog>}
    {selected&&<PartDrawer key={selected} id={selected} role={role} close={close} onUpdated={updated}/>}
  </>;
}
