import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, ClipboardList, Edit3, Hash, MapPin, Package, UserRound } from "lucide-react";
import { RemovalSheet } from "@/components/removal-sheet";
import { ArchiveButton } from "@/components/archive-button";
import { ConditionPill, StatusPill } from "@/components/ui";
import { ItemImage } from "@/components/item-image";
import { requireSession } from "@/lib/auth";
import { getItem } from "@/lib/data";
import { availableQuantity, formatDate, formatDateTime, itemStatus, titleForItem } from "@/lib/utils";
import { reverseMovement } from "@/app/actions/items";

export default async function ItemDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{created?:string;reversed?:string;error?:string}>}){const{id}=await params;const query=await searchParams;const{membership}=await requireSession();const item=await getItem(id);if(!item||item.is_archived)notFound();const movements=item.item_movements||[];const active=movements.filter(m=>m.status==="active");const removed=active.reduce((s,m)=>s+(m.quantity_removed||0),0);const manual=active.some(m=>m.movement_type==="manual_removal");const available=availableQuantity(item.quantity,removed);const gone=itemStatus(item.quantity,removed,manual)!=="Available";const photos=item.item_photos||[];return <div className="mx-auto max-w-6xl">
  <Link href="/parts" className="mb-5 inline-flex min-h-10 items-center gap-2 text-sm font-bold text-slate-500 hover:text-forest-700"><ArrowLeft className="h-4 w-4"/>Parts register</Link>
  {(query.created||query.reversed)&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{query.created?"Part saved to the register.":"Movement reversed and stock restored."}</div>}{query.error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{query.error}</div>}
  <div className="grid gap-6 lg:grid-cols-[minmax(0,1.05fr)_minmax(360px,.95fr)]"><section><ItemImage src={photos[0]?.signed_url} alt={titleForItem(item)} sizes="(max-width:1024px) 100vw, 55vw" className="aspect-[4/3] w-full rounded-2xl shadow-soft"/>{photos.length>1&&<div className="mt-3 grid grid-cols-4 gap-2">{photos.slice(1).map(p=><a href={p.signed_url} target="_blank" rel="noreferrer" key={p.id}><ItemImage src={p.signed_url} alt="Additional part view" className="aspect-square w-full rounded-xl" sizes="160px"/></a>)}</div>}</section>
    <section className="lg:pt-2"><div className="flex flex-wrap gap-2"><StatusPill removed={gone}/><ConditionPill condition={item.condition}/></div><h1 className="mt-4 text-2xl font-black leading-tight tracking-tight sm:text-3xl">{titleForItem(item)}</h1><div className="mt-6 grid grid-cols-2 gap-x-4 gap-y-5 border-y border-slate-200 py-6"><Detail icon={Hash} label="Material number" value={item.material_number}/><Detail icon={ClipboardList} label="WO number" value={item.wo_number}/><div className="col-span-2"><Detail icon={MapPin} label="Location" value={item.location}/></div></div>
      <div className="mt-5 grid grid-cols-3 gap-2"><Metric label="Original" value={item.quantity}/><Metric label="Removed" value={item.quantity===null?(manual?"Yes":"—"):removed}/><Metric label="Available" value={available}/></div>
      <div className="mt-6"><RemovalSheet itemId={item.id} available={gone?0:available}/></div>
      {membership.role==="admin"&&<div className="mt-3 flex flex-col gap-2 sm:flex-row"><Link href={`/parts/${id}/edit`} className="btn-secondary w-full sm:w-auto"><Edit3 className="h-4 w-4"/>Edit details</Link><ArchiveButton itemId={item.id}/></div>}
    </section></div>
  <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><section className="card p-5 sm:p-6"><h2 className="font-bold">Part information</h2><div className="mt-5 space-y-5">{item.notes&&<div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.notes}</p></div>}<div className="flex items-center gap-3 text-sm"><UserRound className="h-4 w-4 text-slate-400"/><div><p className="text-xs text-slate-400">Added by</p><p className="font-semibold">{item.creator?.full_name||item.creator?.email||"Unknown"}</p></div></div><div className="flex items-center gap-3 text-sm"><CalendarDays className="h-4 w-4 text-slate-400"/><div><p className="text-xs text-slate-400">Date added</p><p className="font-semibold">{formatDate(item.created_at)}</p></div></div></div></section>
    <section className="card p-5 sm:p-6"><h2 className="font-bold">Movement history</h2><p className="mt-1 text-xs text-slate-500">A permanent audit trail of use and removal.</p>{!movements.length?<p className="mt-8 rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">No movements recorded yet.</p>:<div className="mt-5 divide-y divide-slate-100">{movements.map(m=><div key={m.id} className="py-4 first:pt-0 last:pb-0"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{m.movement_type==="manual_removal"?"Item marked removed":`${m.quantity_removed} removed`}</p><p className="mt-1 text-xs text-slate-500">{m.remover?.full_name||m.remover?.email||"Unknown"} · {formatDateTime(m.removed_at)}</p>{m.note&&<p className="mt-2 text-sm text-slate-600">{m.note}</p>}</div>{m.status==="reversed"?<span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-500">Reversed</span>:membership.role==="admin"?<form action={reverseMovement.bind(null,item.id,m.id)}><button className="min-h-10 rounded-lg px-3 text-xs font-bold text-red-700 hover:bg-red-50">Reverse</button></form>:null}</div>{m.status==="reversed"&&<p className="mt-2 text-xs text-slate-400">Reversed {m.reversed_at?formatDateTime(m.reversed_at):""} by {m.reverser?.full_name||m.reverser?.email||"admin"}</p>}</div>)}</div>}</section>
  </div>
  </div>}
function Detail({icon:Icon,label,value}:{icon:typeof Package;label:string;value:string|null}){return <div className="flex items-start gap-3"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-slate-400"/><div className="min-w-0"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-700">{value||"Not recorded"}</p></div></div>}
function Metric({label,value}:{label:string;value:number|string|null}){return <div className="rounded-xl bg-white p-3 shadow-soft ring-1 ring-slate-200"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value??"—"}</p></div>}
